// <auto-generated />
namespace Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class m1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m1));
        
        string IMigrationMetadata.Id
        {
            get { return "201309071356590_m1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
